apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-chatbot
  namespace: chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-chatbot
  template:
    metadata:
      labels:
        app: react-chatbot
    spec:
      containers:
      - name: chatbot
        image: chatbot-api
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-chatbot
  namespace: chatbot
spec:
  selector:
    app: react-chatbot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
